name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "Feat:"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add sufficient Screenshot to explain your issue."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I'm GSSOC'24 Extd registered Contributor"
        - label: "I'm Hacktoberfest registered Contributor"
        - label: "I want to work on this issue"